import 'package:hive/hive.dart';

part 'habit.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 2) // Use a new, unique typeId
class Habit extends HiveObject {
  @HiveField(0)
  late String name;

  @HiveField(1)
  late DateTime startDate;

  @HiveField(2)
  late List<DateTime> completions; // List of dates the habit was completed

  @HiveField(3) // Make sure this HiveField index is unique
  int? reminderMinutes;

  Habit({
    required this.name,
    required this.startDate,
    this.completions = const [],
    this.reminderMinutes,
  });

  // Helper method to check if the habit is completed today
  bool isCompletedToday() {
    if (completions.isEmpty) return false;
    final today = DateTime.now();
    return completions.any((date) =>
    date.year == today.year &&
        date.month == today.month &&
        date.day == today.day);
  }

  // Helper method to calculate the current streak
  int get currentStreak {
    if (completions.isEmpty) return 0;
    int streak = 0;
    // Use UTC to avoid timezone issues
    DateTime today = DateTime.utc(DateTime.now().year, DateTime.now().month, DateTime.now().day);

    // Check completions from most recent to oldest
    for (int i = completions.length - 1; i >= 0; i--) {
      DateTime completionDate = DateTime.utc(completions[i].year, completions[i].month, completions[i].day);
      if (completionDate == today.subtract(Duration(days: streak))) {
        streak++;
      } else {
        // As soon as a day is missed, the streak is broken
        break;
      }
    }
    return streak;
  }
}