import 'package:hive/hive.dart';

part 'mood_entry.g.dart'; // To be generated by build_runner

@HiveType(typeId: 3) // Use a new, unique typeId
class MoodEntry extends HiveObject {
  @HiveField(0)
  late DateTime date;

  @HiveField(1)
  late String mood; // e.g., '😊', '😐', '😢'

  MoodEntry({
    required this.date,
    required this.mood,
  });
}